### ISSUE TITLE
Affluent turbidimeter says the desiccant pouch needs to be replaced

### ISSUE THREAD

**Issue by pjm326** [AguaClara/humic_acid#21]
@monroews Do we have extra desiccant pouches? Also replacing the pouches requires opening up the bottom of the turbidimeter, so is there a time that you could swing by to help with that? I wouldn't want to risk accidentally damaging the equipment.

**Comment by monroews** [comment]
the pouch needs to be dried at 100 C for about 24 hours. @caseyching13 could help with that. There is an oven in the Teaching lab (HLS 150).

**Comment by caching13** [comment]
@PeterMcGurk @monroews I will look into this Friday morning

**Comment by caching13** [comment]
@PeterMcGurk Can someone on the team label which turbidimeter is the influent and which is the effluent so that I can remove the correct one?

@monroews Would it be possible to order replacement desiccant pouches so that anyone on the team can switch out desiccant pouches when need be? I believe that another turbidimeter's display stopped working because their desiccant wasn't changed in a timely manner. If we have extra replacement desiccant in the lab, then teams can change the desiccants when need be, and the desiccants can be dried by the TA/other people maintaining the lab. https://store.aquatechnologygroup.com/products/21555r-desiccant-refill-only/#gsc.tab=0

**Comment by pjm326** [comment]
@caseyching13 I can label them at 2:20 when I get out of class.

**Comment by caching13** [comment]
@monroews I've put the desiccant pouch in the oven. Here is another site that sells the desiccant part for the MicroTOL series turbidimeters. https://www.lazenby.net/product/desiccant-refill-only/

**Comment by VanessaQi** [comment]
Thanks Casey!

**Comment by caching13** [comment]
@VanessaQi @PeterMcGurk I've replaced the desiccant pouch in your turbidimeter. If the desc alarm goes off again, please let me know!

**Comment by VanessaQi** [comment]
Okay thanks !
